# Generated by Django 5.2.8 on 2025-12-23 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"managed": False},
        ),
    ]
