# Generated by Django 5.2.8 on 2025-12-24 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_userprofile_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
