# Generated by Django 5.2.8 on 2026-01-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answeroption",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="CorrectAnswer",
        ),
    ]
