# Generated by Django 5.2.8 on 2026-01-08 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_answeroption_is_correct_delete_correctanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="slug",
        ),
    ]
