# Generated by Django 5.2.8 on 2025-12-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_answeroption_correctanswer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionresponse",
            name="selected_choices",
        ),
        migrations.RenameField(
            model_name="answeroption",
            old_name="text",
            new_name="choice_text",
        ),
        migrations.AddField(
            model_name="answeroption",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionresponse",
            name="selected_option",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.answeroption",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
