# Generated by Django 5.2.8 on 2026-01-08 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_course_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="slug",
        ),
    ]
