# Generated by Django 5.2.8 on 2025-12-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_questionresponse_selected_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=10, help_text="Quiz duration in minutes"
            ),
        ),
    ]
