# Generated by Django 5.2.8 on 2026-01-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_moduleprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
