# Generated by Django 5.2.8 on 2026-01-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_quiz_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
