# Generated by Django 5.2.8 on 2025-12-12 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_questionresponse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="attachments",
            field=models.FileField(blank=True, upload_to="lesson_downloads/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="transcripts",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="last_read_position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="resume_time",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("text", "Text"),
                    ("html", "HTML Text"),
                    ("pdf", "PDF/Document"),
                    ("link", "External Link"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
