# Generated by Django 5.2.8 on 2026-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_quiz_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
