# Generated by Django 5.2.8 on 2025-12-15 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_lesson_attachments_lesson_transcripts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="document_file",
        ),
    ]
