# Generated by Django 5.2.8 on 2025-12-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_remove_lesson_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
