# Generated by Django 5.2.8 on 2025-12-17 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_alter_lessonprogress_resume_time_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="instructor",
            new_name="teacher",
        ),
    ]
