# Generated by Django 5.2.8 on 2025-12-18 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_rename_instructor_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
    ]
