# Generated by Django 5.2.8 on 2025-12-23 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_remove_lesson_video_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
